### PR TITLE
Feature/cli sql

### PR DESCRIPTION
**Pull request by aaronbrazell**

### CODE REVIEW

**Comment by aaronbrazell** [comment]
Failed tests here @pdufour. What am I missing?

for WP_VERSION in $WP_VERSIONS; do WP_TESTS_DIR="/tmp/wordpress-tests-lib/${WP_VERSION}"; WP_CORE_DIR="/tmp/wordpress/${WP_VERSION}"; phpunit --debug --log-junit $CIRCLE_TEST_REPORTS/junit/${WP_VERSION}/tests.xml; done
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
PHP Fatal error:  Class 'WP_REST_Server' not found in /tmp/wordpress-tests-lib/includes/spy-rest-server.php on line 3

Fatal error: Class 'WP_REST_Server' not found in /tmp/wordpress-tests-lib/includes/spy-rest-server.php on line 3
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
PHP Fatal error:  Class 'WP_REST_Server' not found in /tmp/wordpress-tests-lib/includes/spy-rest-server.php on line 3

Fatal error: Class 'WP_REST_Server' not found in /tmp/wordpress-tests-lib/includes/spy-rest-server.php on line 3

for WP_VERSION in $WP_VERSIONS; do WP_TESTS_DIR="/tmp/wordpress-tests-lib/${WP_VERSION}"; WP_CORE_DIR="/tmp/wordpress/${WP_VERSION}"; phpunit --debug --log-junit $CIRCLE_TEST_REPORTS/junit/${WP_VERSION}/tests.xml; done returned exit code 255

**Comment by pdufour** [comment]
I updated the `sh` file, I think that should do it.

**Comment by aaronbrazell** [comment]
@pdufour is the only way to kick off another round of testing by pushing a commit?

**Comment by pdufour** [comment]
You can rebuild from the Circle interface, let me do that now.

**Comment by pdufour** [comment]
Schema upgrade function is still there @technosailor

**Pull request closed without merging**
